# 以下除非有说明“可选”，否则均为必填

dbPath: "rabbitool.db" # string，目前只支持sqlite3
redirectUrl: # string，重定向链接用
log:
  consoleLevel: "debug" # log输出到控制台的最低级别，可填"verbose", "debug", "info", "warn", "error", "fatal"
  fileLevel: "info" # log输出到文件的最低级别

notifier: # （可选）用于发生错误时通知的，下面皆指邮箱的配置
  host: # string
  port: # int
  ssl: false # bool
  userName: # string
  password: # string
  from: # string
  to: # string[]
  intervalMinutes: 5 # int，重置积攒的重复通知
  allowedAmount: 25 # int，积攒的重复通知量在规定时间内达到上限后就发送
oss:  # 阿里云对象存储，用于上传图片视频时的暂存空间，同时也用于获取小视频下载直链
  endpoint: # string
  accessKeyId: # string
  accessKeySecret: # string
  bucketName: # string

qqbot:
  appId: # string
  token: # string
  isSandbox: # bool
  sandboxGuildName: # string
youtube:  # （可选）
  apiKey: # string，官方api，参见官方说明
twitter: # （可选）
  token: # string，v2 api
