# 以下除非有说明“可选”，否则均为必填

redirectUrl: # string，重定向链接用
inTestEnvironment: # bool，可选，同时会指定qqbot为sanbox mode
defaultLogger:
  consoleLevel: "debug" # string  # （可选）
  fileLevel: "info" # string  # （可选）
gorm:
  dbPath: "rabbitool.db"  # string，目前只支持sqlite3
  logger: # （可选）
    consoleLevel: "debug" # string  # （可选）
    fileLevel: "info" # string  # （可选）

notifier: # （可选）用于发生错误时通知的，下面皆指邮箱的配置
  host: # string
  port: # int
  ssl: false # bool
  userName: # string
  password: # string
  from: # string
  to: # string[]
  intervalMinutes: 5 # int，重置积攒的重复通知
  allowedAmount: 25 # int，积攒的重复通知量在规定时间内达到上限后就发送
cos: # 腾讯云对象存储，用于上传图片视频时的暂存空间，同时也用于获取小视频下载直链
  secretId: # string
  secretKey: # string
  bucketName: # string
  region: # string


qqbot:
  appId: # string
  token: # string
  sandboxGuildName: # string
  logger: # （可选）
    consoleLevel: "debug" # string  # （可选）
    fileLevel: "info" # string  # （可选）
youtube:  # （可选）
  apiKey: # string，官方api，参见官方说明
twitter: # （可选）
  token: # string，v2 api
