# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Build
      run: go build -o build/rabbitool

    - name: Upload-Files-Action
      uses: zhenyuWang/Upload-File-Action@v1.0.1
      with:
        username: ubuntu
        server: 43.153.177.129
        port: 22
        ssh_private_key: ${{ secrets.id_rsa_github_action }}
        local_path: ./build/rabbitool
        target_path: /home/ubuntu/app/rabbitool/rabbitool
